import { join, preamble, table } from "./doc"

export const INTRO =
  "The wiring that holds a label, a field and its error together. It is react-hook-form under a context, so every part of a field knows its own id and its own error without being told."

export const USE = [
  "`Form` wraps the whole form and takes the object `useForm` returns. Spread it: `<Form {...form}>`. Inside it, one `FormField` per value.",
  "`FormField` binds a field by `name`, takes its `rules`, and hands the bound field to a `render` function. What that function returns is a `FormItem`: the field's own column, with the label, the control and whatever line sits under it 8px apart.",
  "`FormControl` wraps the control and hands it an id, the description and message it is described by, and `aria-invalid`. The control inside it needs none of that passed in, so `<Input {...field} />` is the whole of it.",
  "Error is one state. `FormMessage` reads the error and the field paints itself from the same one, so the box and the words below it cannot disagree. `FormMessage` renders nothing at all when there is no error, so leave it in place rather than adding it conditionally.",
  "`FormLabel` takes an `action`, which is a node pushed to the right end of the label's row. That is where the drawn `Forgot your password?` link sits. Pass an anchor and the row styles it.",
  "`FormDescription` is the helper under the field, and it stays put whether or not there is an error. Put it under the field it explains, or under the pair where a rule covers both.",
  "The parts are not interchangeable with plain markup. A `Label` outside a `FormItem` will not know the field's id, and a control outside a `FormControl` will not be marked invalid.",
]

const FIELD_PROPS: readonly (readonly string[])[] = [
  ["`control`", "`Control`", "none", "From `useForm`, as `form.control`"],
  ["`name`", "`string`", "none", "Which value this field is"],
  ["`render`", "`({ field }) => ReactNode`", "none", "The field's own markup"],
  ["`rules`", "`object`", "none", "Validation, with the message it fails on"],
  [
    "`defaultValue`",
    "`unknown`",
    "none",
    "The starting value for this field alone",
  ],
  [
    "`disabled`",
    "`boolean`",
    "`false`",
    "Disables the field and stops its validation",
  ],
]

const LABEL_PROPS: readonly (readonly string[])[] = [
  [
    "`action`",
    "`ReactNode`",
    "none",
    "A link at the right end of the label's row",
  ],
  ["`children`", "`ReactNode`", "none", "The words"],
  [
    "`className`",
    "`string`",
    "none",
    "Extra classes, for spacing rather than type",
  ],
]

export function formDoc() {
  return join([
    preamble("Form", "component"),
    "",
    "# Form",
    "",
    INTRO,
    "",
    "## Using it",
    "",
    ...USE.flatMap((paragraph) => [paragraph, ""]),
    "```tsx",
    "import {",
    "  Button,",
    "  Form,",
    "  FormControl,",
    "  FormDescription,",
    "  FormField,",
    "  FormItem,",
    "  FormLabel,",
    "  FormMessage,",
    "  Input,",
    '} from "@brevy/ui"',
    'import { Mail } from "lucide-react"',
    'import { useForm } from "react-hook-form"',
    "",
    "export function SignInForm() {",
    '  const form = useForm({ defaultValues: { email: "" } })',
    "",
    "  return (",
    "    <Form {...form}>",
    '      <form className="flex flex-col gap-4" onSubmit={form.handleSubmit(onSubmit)}>',
    "        <FormField",
    "          control={form.control}",
    '          name="email"',
    '          rules={{ required: "Enter your email address." }}',
    "          render={({ field }) => (",
    "            <FormItem>",
    '              <FormLabel action={<a href="/help">Need help?</a>}>',
    "                Email",
    "              </FormLabel>",
    "              <FormControl>",
    "                <Input",
    '                  size="tall"',
    '                  type="email"',
    '                  placeholder="you@example.com"',
    "                  leading={<Mail />}",
    "                  {...field}",
    "                />",
    "              </FormControl>",
    "              <FormDescription>",
    "                We only use this to sign you in.",
    "              </FormDescription>",
    "              <FormMessage />",
    "            </FormItem>",
    "          )}",
    "        />",
    "",
    '        <Button type="submit">Continue</Button>',
    "      </form>",
    "    </Form>",
    "  )",
    "}",
    "```",
    "",
    "## The parts",
    "",
    "- `Form`: the provider. Takes what `useForm` returns.",
    "- `FormField`: one value, bound by name.",
    "- `FormItem`: that field's column.",
    "- `FormLabel`: its label, and an optional link on the same row.",
    "- `FormControl`: wraps the control and wires its id and error.",
    "- `FormDescription`: the helper line under it.",
    "- `FormMessage`: the error, or nothing.",
    "",
    "## Props",
    "",
    "### FormField",
    "",
    table(["Prop", "Values", "Default", "What it does"], FIELD_PROPS),
    "",
    "### FormLabel",
    "",
    table(["Prop", "Values", "Default", "What it does"], LABEL_PROPS),
    "",
    "`FormItem`, `FormControl`, `FormDescription` and `FormMessage` take only",
    "their children and a `className`. Everything else they need comes from the",
    "field around them.",
  ])
}
